const {
  createTrustee,
  getAllTrustees,
  getTrusteeById,
  getTrusteeByCode,
  updateTrustee,
  updateTrusteeStatus,
  getPublicTrustees,
} = require("../models/trusteeModel");

/*
|--------------------------------------------------------------------------
| Add Trustee
|--------------------------------------------------------------------------
*/
const addTrustee = async (req, res) => {
  try {
    const { full_name, mobile_number, designation } = req.body;

    if (!full_name || !mobile_number || !designation) {
      return res.status(400).json({
        success: false,
        message: "Full name, mobile number and designation are required.",
      });
    }

    // Note: trustee_code is auto-generated by createTrustee() itself
    // (VJF0001, VJF0002, ...) after the insert, based on the new row's
    // id — it is never supplied by the client, so there's nothing to
    // check for a duplicate code against at this point.

    const trusteeData = {
      ...req.body,
      profile_image: req.file?.filename || null,
    };

    const trusteeId = await createTrustee(trusteeData);
    const trustee = await getTrusteeById(trusteeId);

    return res.status(201).json({
      success: true,
      message: "Trustee created successfully.",
      data: trustee,
    });
  } catch (error) {
    console.error("Add trustee error:", error);

    return res.status(500).json({
      success: false,
      message: "Failed to create trustee.",
    });
  }
};

/*
|--------------------------------------------------------------------------
| List All Trustees - Admin
|--------------------------------------------------------------------------
*/
const listTrustees = async (req, res) => {
  try {
    const trustees = await getAllTrustees();

    return res.status(200).json({
      success: true,
      data: trustees,
    });
  } catch (error) {
    console.error("List trustees error:", error);

    return res.status(500).json({
      success: false,
      message: "Failed to fetch trustees.",
    });
  }
};

/*
|--------------------------------------------------------------------------
| Get Single Trustee - Admin
|--------------------------------------------------------------------------
*/
const getTrustee = async (req, res) => {
  try {
    const { id } = req.params;

    const trustee = await getTrusteeById(id);

    if (!trustee) {
      return res.status(404).json({
        success: false,
        message: "Trustee not found.",
      });
    }

    return res.status(200).json({
      success: true,
      data: trustee,
    });
  } catch (error) {
    console.error("Get trustee error:", error);

    return res.status(500).json({
      success: false,
      message: "Failed to fetch trustee.",
    });
  }
};

/*
|--------------------------------------------------------------------------
| Edit Trustee
|--------------------------------------------------------------------------
*/
const editTrustee = async (req, res) => {
  try {
    const { id } = req.params;

    const existingTrustee = await getTrusteeById(id);

    if (!existingTrustee) {
      return res.status(404).json({
        success: false,
        message: "Trustee not found.",
      });
    }

    const updatedData = {
      ...existingTrustee,
      ...req.body,
      profile_image: req.file
        ? req.file.filename
        : existingTrustee.profile_image,
    };

    await updateTrustee(id, updatedData);

    const trustee = await getTrusteeById(id);

    return res.status(200).json({
      success: true,
      message: "Trustee updated successfully.",
      data: trustee,
    });
  } catch (error) {
    console.error("Update trustee error:", error);

    return res.status(500).json({
      success: false,
      message: "Failed to update trustee.",
    });
  }
};

/*
|--------------------------------------------------------------------------
| Activate / Deactivate Trustee
|--------------------------------------------------------------------------
*/
const changeTrusteeStatus = async (req, res) => {
  try {
    const { id } = req.params;
    const { is_active } = req.body;

    if (
      is_active !== true &&
      is_active !== false &&
      is_active !== 1 &&
      is_active !== 0
    ) {
      return res.status(400).json({
        success: false,
        message: "Valid is_active value is required.",
      });
    }

    const trustee = await getTrusteeById(id);

    if (!trustee) {
      return res.status(404).json({
        success: false,
        message: "Trustee not found.",
      });
    }

    const status =
      is_active === true || Number(is_active) === 1 ? 1 : 0;

    await updateTrusteeStatus(id, status);

    return res.status(200).json({
      success: true,
      message: status
        ? "Trustee activated successfully."
        : "Trustee deactivated successfully.",
    });
  } catch (error) {
    console.error("Trustee status error:", error);

    return res.status(500).json({
      success: false,
      message: "Failed to update trustee status.",
    });
  }
};

/*
|--------------------------------------------------------------------------
| Public Trustees
|--------------------------------------------------------------------------
*/
const publicTrustees = async (req, res) => {
  try {
    const trustees = await getPublicTrustees();

    return res.status(200).json({
      success: true,
      data: trustees,
    });
  } catch (error) {
    console.error("Public trustees error:", error);

    return res.status(500).json({
      success: false,
      message: "Failed to fetch trustees.",
    });
  }
};

module.exports = {
  addTrustee,
  listTrustees,
  getTrustee,
  editTrustee,
  changeTrusteeStatus,
  publicTrustees,
};